# ==========================
# PostgreSQL (Neon)
# ==========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================
# JPA Configuration
# ==========================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# Weather API
# ==========================
weather.api.key=${WEATHER_API_KEY}

# ==========================
# Server
# ==========================
<<<<<<< HEAD
server.port=${PORT:8080}
=======
server.port=${PORT:8080}
>>>>>>> 2aab438793f155a2441fc98018f53fc3ac8e4bd7
