spring.application.name=kisansakthi

# Active profile (dev locally, prod on Render)
<<<<<<< HEAD
spring.profiles.active=${SPRING_PROFILES_ACTIVE:prod}
=======
spring.profiles.active=${SPRING_PROFILES_ACTIVE:prod}
>>>>>>> 2aab438793f155a2441fc98018f53fc3ac8e4bd7
